---

- name: Initial configuration for a {{ application_name }} server
  hosts: all
  become: true
  become_user: root
  remote_user: "{{ server_user }}"
  gather_facts: no # disable to allow user setup
  vars:
    - update_apt_cache: true
  vars_files:
    - roles/base/defaults/main.yml
    - env_vars/{{ env }}.yml

  roles:
    - security
