---

- name: Provision a web server
  hosts: webservers
  become: true
  become_user: root
  remote_user: "{{ server_user }}"
  vars:
    update_apt_cache: true
  vars_files:
    - env_vars/{{ env }}.yml

  roles:
    - base
    - certbot
    - redis
    - rabbitmq
    - node
    - web
    - celery
    - nginx
