---

# Virtualenv settings.
enable_deadsnakes_ppa: false
recreate_virtualenv: false
virtualenv_python_version: "{{ base_python_package }}"


# Application settings.
virtualenv_path: "/webapps/{{ application_name }}"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
application_log_dir: "{{ virtualenv_path }}/logs"
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
requirements_file: "{{ project_path }}/requirements/production.txt"


# Gunicorn settings.
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps


# Nginx settings.
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ project_path }}/staticfiles/"
nginx_media_dir: "{{ project_path }}/media/"


# Django environment variables.
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_ADMIN_URL: "{{ django_admin_url }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  DJANGO_ALLOWED_HOSTS: "{{ site_host }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_URL: "postgres://{{ db_user }}:{{ db_password }}@localhost/{{ db_name }}"
  REDIS_URL: "redis://localhost:6379"
  CELERY_BROKER_URL: "{{ broker_url }}"
  MAILJET_API_KEY: "{{ mailjet_api_key }}"
  MAILJET_SECRET_KEY: "{{ mailjet_secret_key }}"
